# Generated by Django 5.2.17 on 2026-10-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externo',
            name='procedencia',
        ),
        migrations.AddField(
            model_name='externo',
            name='tipo_experiencia',
            field=models.CharField(default='Experiencia propia', max_length=50),
        ),
        migrations.AddField(
            model_name='instructor',
            name='procedencia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
