# Generated by Django 5.2.17 on 2026-09-21 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudExpositor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semblanza', models.TextField(help_text='Descripción detallada o currículum del expositor.')),
                ('organizacion', models.CharField(blank=True, help_text='Nombre de la empresa o institución (opcional).', max_length=255, null=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobada'), ('REC', 'Rechazada')], default='PEN', max_length=30)),
                ('enlaces_redes', models.JSONField(blank=True, default=dict, help_text="Almacena enlaces en formato clave-valor (ej. {'linkedin': 'url', 'twitter': 'url'}).")),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_expositor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
